name: Frontend-CI

on:
  workflow_dispatch:
  push:
    branches: ["main"]
    paths:
      - frontend_website/**
  pull_request:
    branches: ["main"]
    paths:
      - frontend_website/**

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: setup node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
          cache-dependency-path: frontend_website/package-lock.json

      - name: install dependencies
        working-directory: ./frontend_website
        run: |
          npm install
          npm ci
        #working-directory: ./frontend_website

      - name: build and test
        working-directory: ./frontend_website
        run: |
          npm run build --if-present
        #npm test

  dockerise:
    runs-on: ubuntu-latest
    needs: [build_and_test]
    steps:
      - name: Docker Login
        uses: docker/login-action@v2.1.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Code Checkout
        uses: actions/checkout@v2.5.0
      - name: Setup QEMU
        uses: docker/setup-qemu-action@v2.1.0
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2.2.1
      - name: Build and Push
        uses: docker/build-push-action@v3.2.0
        with:
          context: "frontend_website/"
          file: "frontend_website/Dockerfile"
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/opspad-frontend:latest
